default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  username: <%= ENV.fetch("DB_USERNAME", "roshanshah") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: railshouse_development
  port: <%= ENV.fetch("DB_PORT", 5433) %>

test:
  <<: *default
  database: railshouse_test
  port: <%= ENV.fetch("DB_PORT", 5433) %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
